# -*- coding: utf-8 -*-
"""Open Ended Lab (DSA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFPGlENRcEDEBy7autEme-deNnRy_2_W
"""

class node:
      def __init__(self,data):
#linking it with the next node
          self.head=data
          self.next=None

class linkedlist:

      def __init__(self):
#creating a head
          self.head=None
          self.n=None
          self.m=None

      def insert(self,data):
# adding data to the linked list
          add=node(data)
          if self.head==None:
             self.head=add
          else:
             current.self.head
             while current.next:
                   current=current.next
                   current=self.head
                   current.next=add
      def display(self):
        if self.head==None:
          print("it is empty")
        else:
            current=self.head
        while current:
              print(current.data)
              current=current.next
      def delete(self):
        #delete m nodes
          self.m=input("enter node to delete")
          if self.head==empty:
             print("its is empty")
          else:
             del(self.data)
      def skip(self):
         #nodes to skip
          self.n=input("enter node to skip")
          print(self.data-self.n)


a1=linkedlist()
a1.insert(3)
a1.insert(4)
a1.insert(5)
a1.insert(6)
a1.display()
a1.delete()
a1.skip()